<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mewajibkan_css-12tb2l0-unf-radio__area_1035fc</name>
   <tag></tag>
   <elementGuidId>fa3c8468-8ec0-4135-8dfd-166eb8df7b82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='weightShippingSection']/div[3]/div[2]/div/div[2]/div/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-aplaht > div.css-1bh52ki.e12o1eyi0 > label.css-14vgcl7-unf-radio.e12o1eyi3 > span.css-12tb2l0-unf-radio__area.e12o1eyi1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-12tb2l0-unf-radio__area e12o1eyi1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weightShippingSection&quot;)/div[@class=&quot;css-1rlxqts&quot;]/div[2]/div[@class=&quot;css-1xhj18k&quot;]/div[@class=&quot;css-aplaht&quot;]/div[@class=&quot;css-1bh52ki e12o1eyi0&quot;]/label[@class=&quot;css-14vgcl7-unf-radio e12o1eyi3&quot;]/span[@class=&quot;css-12tb2l0-unf-radio__area e12o1eyi1&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weightShippingSection']/div[3]/div[2]/div/div[2]/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
