<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>0db0e7f2-17a0-4126-8ab1-dae7121b8d1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-1o52sjq > svg.unf-icon > path</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M20 5.09h-4.95v-.1A3.025 3.025 0 109 5v.1H4a1 1 0 000 2h1v13A1.84 1.84 0 006.92 22h10.16A1.902 1.902 0 0019 20.09V7.1h1a1 1 0 100-2v-.01zM11 5a1 1 0 012 0v.1h-2V5zM7 20V7.1h10V20H7zm3-2a1 1 0 001-1v-6.9a1 1 0 00-2 0V17a1 1 0 001 1zm4.767-.293A1 1 0 0113.06 17v-6.9a1 1 0 112 0V17a1 1 0 01-.293.707z</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;merchant-root&quot;)/div[@class=&quot;css-ethtfe is-open&quot;]/div[@class=&quot;content-container&quot;]/div[@class=&quot;css-qodsfp&quot;]/section[@class=&quot;css-r8b4d8-unf-card eyk31ek0&quot;]/div[@class=&quot;css-1gbu4dk&quot;]/div[2]/div[1]/div[@class=&quot;css-9m08hc&quot;]/div[@class=&quot;css-3b0zis e19by5ca0&quot;]/div[@class=&quot;css-jvy6cf e19by5ca1&quot;]/div[@class=&quot;css-24ehv5 e19by5ca1&quot;]/div[@class=&quot;css-1iqb1tn&quot;]/div[@class=&quot;css-1o52sjq&quot;]/svg[@class=&quot;unf-icon&quot;]/path[1]</value>
   </webElementProperties>
</WebElementEntity>
